#!/usr/bin/env sh

FILES=$(git diff --cached --name-only)
ROOT=$(git rev-parse --show-toplevel)

if echo "$FILES" | grep -qE "\.(js|ts|jsx|tsx)$"; then
  cd "$ROOT"/client
  bin_path=$(which bun)
  bin_name="bun"

  if [ -n "$bin_path" ]; then
    bun run lint
  else 
    bin_name="npm"
    npm run lint
  fi

  if [ $? -ne 0 ]; then
    echo "You can run \"$bin_name run lint:write\" to fix some errors!"
    exit 1
  fi
fi

if echo "$FILES" | grep -q "\.go$"; then
  cd "$ROOT"/server
  go_path="$(which go)"
  if [ -z "$go_path" ]; then
    echo "You must have go installed!"
    exit 1
  fi

  changed_files=$(go fmt ./...)

  bin_path="$(go env GOPATH)/bin/revive"
  if [ ! -f "$bin_path" ]; then
    echo "Installing linter"
    go install github.com/mgechev/revive@latest
  fi

  "$bin_path" -formatter friendly ./...
  if [ -n "$changed_files" ]; then
    git add "$changed_files"
  fi

  if [ $? -ne 0 ]; then
    exit 1
  fi
fi
